---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  A macro for deploying tempate resources in parallel by managing DependsOn
Resources:
  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: CfConcurrencyMacro
      FunctionName: !GetAtt CfConcurrencyMacroFunction.Arn
  CfConcurrencyMacroFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cf_concurrency_macro.py
      Handler: cf_concurrency_macro.handler
      Runtime: python3.7
      Timeout: 5