---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  A macro for deploying tempate resources in parallel by managing DependsOn
Resources:
  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: ParallelizerMacro
      FunctionName: !GetAtt ParallelizerMacroFunction.Arn
  ParallelizerMacroFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: parallelizer_macro.py
      Handler: parallelizer_macro.handler
      Runtime: python3.7
      Timeout: 5